const SIGNING_IN = 'SIGNING_IN'
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
const SIGN_IN_ERROR = 'SIGN_IN_ERROR'

const SIGNING_OUT = 'SIGNING_OUT'
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR'

const FETCH_ORDERS = 'FETCH_ORDERS'
const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR'

const FETCH_ORDER = 'FETCH_RECIPE'
const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
const FETCH_ORDER_ERROR = 'FETCH_ORDER_ERROR'

export default {
  SIGNING_IN,
  SIGN_IN_SUCCESS,
  SIGN_IN_ERROR,
  SIGNING_OUT,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_ERROR,
  FETCH_ORDERS,
  FETCH_ORDERS_SUCCESS,
  FETCH_ORDERS_ERROR,
  FETCH_ORDER,
  FETCH_ORDER_SUCCESS,
  FETCH_ORDER_ERROR
}
